apiVersion: v1
kind: Service
metadata:
  name: feature-store-api
  namespace: feature-store

spec:
  selector:
    app: feature-store-api

  ports:
  - port: 80
    targetPort: 8000

  type: ClusterIP
