apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: feature-store-api
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: feature-store-api
  namespaceSelector:
    matchNames:
      - feature-store
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
