name: Feature Store CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: feature-store-api
  CLUSTER_NAME: feature-store-lab

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::497508796460:role/GitHubActionsEKSRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest Tests/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 497508796460.dkr.ecr.ap-south-1.amazonaws.com/feature-store-api:${{ github.sha }}
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --name $CLUSTER_NAME \
            --region $AWS_REGION

      - name: Deploy
        run: |
          kubectl set image deployment/feature-store-api \
          feature-store-api=497508796460.dkr.ecr.ap-south-1.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }} \
          -n feature-store

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/feature-store-api \
          -n feature-store
